---
- name: Deploy a Simple Web Application
  hosts: 192.168.18.121
  become: true

  tasks:
    - name: Ensure Nginx is installed
      dnf:
        name: nginx
        state: present

    - name: Deploy custom HTML index page
      copy:
        content: "<h1>Hello World! App deployed via Ansible.</h1>"
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Ensure Nginx is running and enabled on boot
      service:
        name: nginx
        state: started
        enabled: true
