---
- name: Deploy a Simple Web Application
  hosts: 192.168.18.121
  become: true

  tasks:
    - name: Install Python
      apt: 
        name: python3-apt
        state: present
        update_cache: true
        
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Deploy custom HTML index page
      copy:
        content: "<h1>Hello World! App deployed via Ansible.</h1>"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure Nginx is running and enabled on boot
      service:
        name: nginx
        state: started
        enabled: true
